In [1]:
#necessary libraries
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import decode_predictions
from keras.applications.vgg16 import preprocess_input
from keras.preprocessing import image
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Model
import datetime
import numpy as np
import os
import tensorflow as tf
import matplotlib.pyplot as plt
from tqdm import tqdm
#import cv2
#import PIL.Image
import matplotlib 
import seaborn as sns
from IPython.display import display
import matplotlib.pyplot as plt
%matplotlib inline
import shutil
import posixpath
import sys 
import glob
#import wfdb
import pandas as pd
import math
#from PIL import Image

In [2]:
import tensorflow as tf
from tensorflow import keras
from keras.applications.resnet50 import ResNet50
from keras.applications.resnet50 import preprocess_input, decode_predictions
from tensorflow.keras import layers, saving
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam, SGD
import numpy as np
from keras.models import Sequential

In [3]:
tf.compat.v1.ConfigProto( device_count = {'GPU': 1 , 'CPU': 10})

device_count {
  key: "CPU"
  value: 10
}
device_count {
  key: "GPU"
  value: 1
}

In [7]:
def predict_image(image_path, model):   ##overload function
    img = image.load_img(image_path, target_size=(224, 224, 3))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    preds = model.predict(x)
    return preds

## _FEATURE IMAGE BASED MODEL, 5 CHANNELS UNDER HERMITE TRANSFORM, 2 CLASSES_

In [4]:
##load model
model = keras.saving.load_model('./models/resnet50_multi_images.keras')

In [7]:
predict_image('sample_ecg_1089.png')  ##new model---image based

1/1 ━━━━━━━━━━━━━━━━━━━━ 19s 19s/step


array([[6.997472e-23, 1.000000e+00]], dtype=float32)

In [8]:
predict_image('sample_ecg_0.png')   ##new model---image based

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 255ms/step


array([[1.4106507e-12, 1.0000000e+00]], dtype=float32)

In [9]:
predict_image('./ptb_ecg_filtered/train_multi/Healthy control/948_multiple_ Healthy control.png')##new model---image based

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 203ms/step


array([[0.97279197, 0.02720801]], dtype=float32)

In [10]:
predict_image('12_sick_single.png')##new model---image based

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 278ms/step


array([[2.6409014e-20, 1.0000000e+00]], dtype=float32)

## _CHANNEL IMAGE BASED MODEL, 3 SEPARATE CHANNELS WITHOUT BASELINE, 2 CLASSES_

In [4]:
##load model
model_ii = keras.saving.load_model('./models/resnet50_ii_images.keras')

In [8]:
predict_image('./ptb_resnet_rerun/second_arch/ii/Myocardial Infarction/1.csv.png', model_ii)

1/1 ━━━━━━━━━━━━━━━━━━━━ 20s 20s/step


array([[6.3056373e-34, 1.0000000e+00]], dtype=float32)

In [10]:
##load model
model_v6 = keras.saving.load_model('./models/resnet50_v6_images.keras')

In [11]:
predict_image('./ptb_resnet_rerun/second_arch/v6/Myocardial Infarction/1.csv.png', model_v6)

1/1 ━━━━━━━━━━━━━━━━━━━━ 23s 23s/step


array([[4.3788358e-32, 1.0000000e+00]], dtype=float32)

In [12]:
##load model
model_vz = keras.saving.load_model('./models/resnet50_vz_images.keras')

ValueError: Expected a model.weights.h5 or model.weights.npz file.

In [ ]:
predict_image('./ptb_resnet_rerun/second_arch/vz/Healthy control/948.csv.png', model_vz)

## _DELETED MODEL: FEATURE IMAGE BASED MODEL, 5 CHANNELS UNDER HERMITE TRANSFORM, 15 CLASSES_

In [5]:
def max_class_prob(predictions):
    _max = max(predictions[0])
    solution = 0
    for i in range(1, len(predictions[0])):
        if predictions[0][i] == _max:
            solution = i
        continue
            
    return _max, solution

In [47]:
##old model
img_path = './ptb_ecg_filtered/train_multi/Myocardial Infarction/16_multiple_ Myocardial infarction.png'
img = keras.utils.load_img(img_path, target_size=(224, 224))
x = keras.utils.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = loaded_model.predict(x, batch_size=32)
print('Predicted:', preds)
_max, soln = max_class_prob(preds)
print('Max probability is at class number:', soln)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step
Predicted: [[0.0000000e+00 0.0000000e+00 1.9870746e-25 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]]
Max probability is at class number: 8


In [48]:
##old model
img_path = './ptb_ecg_filtered/train_multi/Healthy control/949_multiple_ Healthy control.png'
img = keras.utils.load_img(img_path, target_size=(224, 224))
x = keras.utils.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = loaded_model.predict(x, batch_size=32)
print('Predicted:', preds)
_max, soln = max_class_prob(preds)
print('Max probability is at class number:', soln)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step
Predicted: [[0.0000000e+00 1.7003404e-34 9.2071768e-28 1.1895526e-21 0.0000000e+00
  0.0000000e+00 0.0000000e+00 4.7863273e-27 1.0000000e+00 4.1757647e-32
  0.0000000e+00 5.7787904e-34 2.3793084e-38 0.0000000e+00 7.7073503e-32]]
Max probability is at class number: 8


In [50]:
##old model
img_path = './ptb_ecg_filtered/train_multi/Bundle branch block/1164_multiple_ Bundle branch block.png'
img = keras.utils.load_img(img_path, target_size=(224, 224))
x = keras.utils.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = loaded_model.predict(x, batch_size=32)
print('Predicted:', preds)
_max, soln = max_class_prob(preds)
print('Max probability is at class number:', soln)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 222ms/step
Predicted: [[0.0000000e+00 0.0000000e+00 2.6503566e-21 3.1790779e-27 4.9160409e-36
  0.0000000e+00 3.4473655e-37 6.3377441e-31 1.0000000e+00 7.2800549e-37
  0.0000000e+00 9.3668962e-32 0.0000000e+00 0.0000000e+00 3.1520013e-29]]
Max probability is at class number: 8
