In [1]:
#necessary libraries
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import decode_predictions
from keras.applications.vgg16 import preprocess_input
from keras.preprocessing import image
from tensorflow.keras.layers import Input, Conv2D, MaxPooling2D
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.models import Model
import datetime
import numpy as np
import os
import tensorflow as tf
import matplotlib.pyplot as plt
from tqdm import tqdm
#import cv2
#import PIL.Image
import matplotlib 
import seaborn as sns
from IPython.display import display
import matplotlib.pyplot as plt
%matplotlib inline
import shutil
import posixpath
import sys 
import glob
#import wfdb
import pandas as pd
import math
#from PIL import Image

In [2]:
import tensorflow as tf
from tensorflow import keras
from keras.applications.resnet50 import ResNet50
from keras.applications.resnet50 import preprocess_input, decode_predictions
from tensorflow.keras import layers, saving
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam, SGD
import numpy as np
from keras.models import Sequential

In [3]:
tf.compat.v1.ConfigProto( device_count = {'GPU': 1 , 'CPU': 10})

device_count {
  key: "CPU"
  value: 10
}
device_count {
  key: "GPU"
  value: 1
}

In [4]:
def predict_image(image_path, model):   ##overload function
    img = image.load_img(image_path, target_size=(224, 224, 3))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)
    x = preprocess_input(x)
    preds = model.predict(x)
    return preds

In [48]:
def disease_predict(array):
    label = 0
    for i in range(0,2):
        if array[0][0] < array[0][1] :
            label = 1

    return label

def generate_label(predict_list):
    threshold = 2/3 * len(predict_list)
    count_ones = sum(1 for x in predict_list if x == 1)
    
    if count_ones >= threshold:
        return 1
    else:
        return 0

## _FEATURE IMAGE BASED MODEL, 5 CHANNELS UNDER HERMITE TRANSFORM, 2 CLASSES_

In [7]:
##load model
model = keras.saving.load_model('./models/resnet50_multi_images.keras')

In [9]:
predict_image('sample_ecg_1089.png', model)  ##new model---image based

1/1 ━━━━━━━━━━━━━━━━━━━━ 16s 16s/step


array([[6.996937e-23, 1.000000e+00]], dtype=float32)

In [10]:
print(disease_predict([[6.996937e-23, 1.000000e+00]]))

1


In [12]:
print(disease_predict(predict_image('sample_ecg_0.png', model)))   ##new model---image based

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 383ms/step
1


In [13]:
print(disease_predict(predict_image('./ptb_ecg_filtered/train_multi/Healthy control/948_multiple_ Healthy control.png', model)))##new model---image based

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 302ms/step
0


In [14]:
print(disease_predict(predict_image('12_sick_single.png',model)))##new model---image based

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 229ms/step
1


## _CHANNEL IMAGE BASED MODEL, 3 SEPARATE CHANNELS WITHOUT BASELINE, 2 CLASSES_

In [6]:
##load model
model_ii = keras.saving.load_model('./models/resnet50_ii_images.keras')

In [8]:
predict_image('./ptb_resnet_rerun/second_arch/ii/Myocardial Infarction/1.csv.png', model_ii)

1/1 ━━━━━━━━━━━━━━━━━━━━ 25s 25s/step


array([[6.3049146e-34, 1.0000000e+00]], dtype=float32)

In [9]:
predict_image('./ptb_resnet_rerun/second_arch/ii/Myocardial Infarction/0.csv.png', model_ii)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 314ms/step


array([[6.3049146e-34, 1.0000000e+00]], dtype=float32)

In [7]:
##load model
model_v6 = keras.saving.load_model('./models/resnet50_v6_images.keras')

In [11]:
predict_image('./ptb_resnet_rerun/second_arch/v6/Myocardial Infarction/1.csv.png', model_v6)

1/1 ━━━━━━━━━━━━━━━━━━━━ 24s 24s/step


array([[4.378668e-32, 1.000000e+00]], dtype=float32)

In [12]:
predict_image('./ptb_resnet_rerun/second_arch/v6/Myocardial Infarction/1.csv.png', model_ii)

1/1 ━━━━━━━━━━━━━━━━━━━━ 17s 17s/step


array([[1.0320764e-33, 1.0000000e+00]], dtype=float32)

In [14]:
predict_image('./ptb_resnet_rerun/second_arch/v6/Myocardial Infarction/1.csv.png', model_vz)

1/1 ━━━━━━━━━━━━━━━━━━━━ 28s 28s/step


array([[1.17746896e-32, 1.00000000e+00]], dtype=float32)

In [8]:
##load model
model_vz = keras.saving.load_model('./models/resnet50_vz_images.keras')

In [7]:
predict_image('./ptb_resnet_rerun/second_arch/vz/Healthy control/948.csv.png', model_vz)

1/1 ━━━━━━━━━━━━━━━━━━━━ 21s 21s/step


array([[5.920146e-10, 1.000000e+00]], dtype=float32)

In [30]:
sample_label = disease_predict(predict_image('./ptb_resnet_rerun/second_arch/vz/Myocardial Infarction/1.csv.png', model_vz))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 293ms/step


In [31]:
sample_label

1

#  INTEGRATE TEST

## Load ecg leads models

## Load risk factor model

In [9]:
%run E:/Jupyter/A_DNN/risk_factors/risk_factors.py
filename = './models/gradient_boost_model.sav'
risk_model = pickle.load(open(filename, 'rb')) 

    age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  51.0  1.0  4.0     140.0  299.0  0.0      0.0    173.0    1.0      1.6   
1  59.0  1.0  4.0     110.0  239.0  0.0      2.0    142.0    1.0      1.2   
2  70.0  1.0  4.0     130.0  322.0  0.0      2.0    109.0    0.0      2.4   
3  52.0  1.0  2.0     128.0  205.0  1.0      0.0    184.0    0.0      0.0   
4  60.0  1.0  4.0     145.0  282.0  0.0      2.0    142.0    1.0      2.8   

   slope   ca  thal  num age_category  total_risk  exercise_angina  \
0    1.0  0.0   7.0    1  Middle-aged       439.0             True   
1    2.0  1.0   7.0    1  Middle-aged       349.0            False   
2    2.0  3.0   3.0    1       Senior       452.0            False   
3    1.0  0.0   3.0    0  Middle-aged       333.0            False   
4    2.0  2.0   7.0    1       Senior       427.0            False   

   cholesterol_hdl_ratio  
0               1.728324  
1               1.683099  
2               2.954128  
3       

## In case of 0, 0:

In [11]:
sample_0_0 = []
sample_0_0.append(disease_predict(predict_image('./integration test/0_0/1007_ii.png', model_ii)))
sample_0_0.append(disease_predict(predict_image('./integration test/0_0/1007_v6.png', model_v6)))
sample_0_0.append(disease_predict(predict_image('./integration test/0_0/1007_vz.png', model_vz)))
print(sample_0_0)

1/1 ━━━━━━━━━━━━━━━━━━━━ 24s 24s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 12s 12s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 11s 11s/step
[1, 1, 1]


In [49]:
generate_label(sample_0_0)   ##final ECG label

1

In [26]:
import numpy as np
import pandas as pd

In [28]:
file_path = "./integration test/0_0/patient1.csv"
df = pd.read_csv(file_path) 

In [29]:
X_test_1 = df
y_test_1 = []
y_pred = risk_model.predict(X_test_1)
y_pred

array([0], dtype=int64)

In [50]:
generate_label(y_pred) ##final risk label

0

In [56]:
##get intermediate label
#intermediate = 0
if ((generate_label(y_pred) == 0 and generate_label(sample_0_0) == 1)
    or (generate_label(y_pred) == 1 and generate_label(sample_0_0) == 1)):
    intermediate = 1
else:
    intermediate = 0

print("Intermediate label is:", intermediate)


def intermediate_label(y_pred, sample):
    if ((generate_label(y_pred) == 0 and generate_label(sample) == 1)
    or (generate_label(y_pred) == 1 and generate_label(sample) == 1)):
        intermediate = 1
    else:
        intermediate = 0

    print("Intermediate label is:", intermediate)

Intermediate label is: 1


## In case of 0, 1:

In [52]:
## 1
sample_0_1 = []
sample_0_1.append(disease_predict(predict_image('./integration test/0_1/142_ii.png', model_ii)))
sample_0_1.append(disease_predict(predict_image('./integration test/0_1/142_v6.png', model_v6)))
sample_0_1.append(disease_predict(predict_image('./integration test/0_1/142_vz.png', model_vz)))
print(sample_0_1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 13s 13s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 8s 8s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
[1, 1, 1]


In [53]:
generate_label(sample_0_1)   ##final ECG label

1

In [54]:
file_path = "./integration test/0_0/patient1.csv"
df = pd.read_csv(file_path) 
X_test_1 = df
y_test_1 = []
y_pred = risk_model.predict(X_test_1)
y_pred

array([0], dtype=int64)

In [55]:
generate_label(y_pred) ##final risk label

0

In [57]:
intermediate_label(y_pred, sample_0_1)

Intermediate label is: 1


## In case of 1, 0:

In [58]:
sample_1_0 = []
sample_1_0.append(disease_predict(predict_image('./integration test/1_0/948_ii.png', model_ii)))
sample_1_0.append(disease_predict(predict_image('./integration test/1_0/948_v6.png', model_v6)))
sample_1_0.append(disease_predict(predict_image('./integration test/1_0/948_vz.png', model_vz)))
print(sample_1_0)

1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
[1, 1, 1]


In [59]:
generate_label(sample_1_0)   ##final ECG label

1

In [61]:
file_path = "./integration test/1_0/patient1.csv"
df = pd.read_csv(file_path) 
X_test_1 = df
y_test_1 = []
y_pred = risk_model.predict(X_test_1)
y_pred

array([1], dtype=int64)

In [62]:
generate_label(y_pred) ##final risk label

1

In [63]:
intermediate_label(y_pred, sample_1_0)

Intermediate label is: 1


## In case of 1, 1:

In [64]:
## 1
sample_1_1 = []
sample_1_1.append(disease_predict(predict_image('./integration test/1_1/394_ii.png', model_ii)))
sample_1_1.append(disease_predict(predict_image('./integration test/1_1/394_v6.png', model_v6)))
sample_1_1.append(disease_predict(predict_image('./integration test/1_1/394_vz.png', model_vz)))
print(sample_1_1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 14s 14s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step
[1, 1, 1]


In [65]:
generate_label(sample_1_1)   ##final ECG label

1

In [66]:
file_path = "./integration test/1_1/patient1.csv"
df = pd.read_csv(file_path) 
X_test_1 = df
y_test_1 = []
y_pred = risk_model.predict(X_test_1)
y_pred

array([1], dtype=int64)

In [67]:
generate_label(y_pred) ##final risk label

1

In [68]:
intermediate_label(y_pred, sample_1_1)

Intermediate label is: 1


## _DELETED MODEL: FEATURE IMAGE BASED MODEL, 5 CHANNELS UNDER HERMITE TRANSFORM, 15 CLASSES_

In [5]:
def max_class_prob(predictions):
    _max = max(predictions[0])
    solution = 0
    for i in range(1, len(predictions[0])):
        if predictions[0][i] == _max:
            solution = i
        continue
            
    return _max, solution

In [47]:
##old model
img_path = './ptb_ecg_filtered/train_multi/Myocardial Infarction/16_multiple_ Myocardial infarction.png'
img = keras.utils.load_img(img_path, target_size=(224, 224))
x = keras.utils.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = loaded_model.predict(x, batch_size=32)
print('Predicted:', preds)
_max, soln = max_class_prob(preds)
print('Max probability is at class number:', soln)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 171ms/step
Predicted: [[0.0000000e+00 0.0000000e+00 1.9870746e-25 0.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 1.0000000e+00 0.0000000e+00
  0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00 0.0000000e+00]]
Max probability is at class number: 8


In [48]:
##old model
img_path = './ptb_ecg_filtered/train_multi/Healthy control/949_multiple_ Healthy control.png'
img = keras.utils.load_img(img_path, target_size=(224, 224))
x = keras.utils.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = loaded_model.predict(x, batch_size=32)
print('Predicted:', preds)
_max, soln = max_class_prob(preds)
print('Max probability is at class number:', soln)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step
Predicted: [[0.0000000e+00 1.7003404e-34 9.2071768e-28 1.1895526e-21 0.0000000e+00
  0.0000000e+00 0.0000000e+00 4.7863273e-27 1.0000000e+00 4.1757647e-32
  0.0000000e+00 5.7787904e-34 2.3793084e-38 0.0000000e+00 7.7073503e-32]]
Max probability is at class number: 8


In [50]:
##old model
img_path = './ptb_ecg_filtered/train_multi/Bundle branch block/1164_multiple_ Bundle branch block.png'
img = keras.utils.load_img(img_path, target_size=(224, 224))
x = keras.utils.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = loaded_model.predict(x, batch_size=32)
print('Predicted:', preds)
_max, soln = max_class_prob(preds)
print('Max probability is at class number:', soln)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 222ms/step
Predicted: [[0.0000000e+00 0.0000000e+00 2.6503566e-21 3.1790779e-27 4.9160409e-36
  0.0000000e+00 3.4473655e-37 6.3377441e-31 1.0000000e+00 7.2800549e-37
  0.0000000e+00 9.3668962e-32 0.0000000e+00 0.0000000e+00 3.1520013e-29]]
Max probability is at class number: 8
